
title: QA Site for Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

repo_name: "This-should-be-overridden-by-github-actions-script"

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "This-should-be-overridden-by-github-actions-script"
repo: ucsb-cs156-s23/STARTER-team02
owner: ucsb-cs156-s23
repo_name: STARTER-team02
pull_requests: [{"author":{"is_bot":true,"login":"app/dependabot"},"headRefName":"dependabot/npm_and_yarn/frontend/minimist-1.2.8","number":1,"title":"Bump minimist from 1.2.5 to 1.2.8 in /frontend","url":"https://github.com/ucsb-cs156-s23/STARTER-team02/pull/1"}]
